name: creeperbomb
main: com.jeroensteenbeeke.bk.creeperbomb.Plugin
version: 1.0-SNAPSHOT

commands:
  creeperbomb:
    description: Surrounds a given player with creepers
    permission: creeperbomb.use
    usage: |
        /creeperbomb <player> <radius>
permissions:
    creeperbomb.use:
         description: Allows you to create a creeperbomb
         default: false