#
# This file is part of Jaybukkit.
#
# Jaybukkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Jaybukkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Jaybukkit.  If not, see <http://www.gnu.org/licenses/>.
#

name: jaymail
main: com.jeroensteenbeeke.bk.jaymail.JaymailPlugin
version: 1.0-SNAPSHOT
database: true

commands:
    mail-send:
        description: Sends a mail to another person
        permission: jaymail.mail
        usage: /mail-send <player> <message>
    mail-read:
        description: Reads a mail from your inbox
        permission: jaymail.mail
        usage: /mail-read <number>
    mail-delete:
        description: Sends a mail to another person
        permission: jaymail.mail
        usage: /mail-delete <player> <message>
    mail:
        description: Shows whether or not you have mail waiting 
        permission: jaymail.mail
        usage: /mail
permissions:
    jaymail.mail:
        description: Gives users access to their e-mail
        default: false