#
# This file is part of Jaybukkit.
#
# Jaybukkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Jaybukkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Jaybukkit.  If not, see <http://www.gnu.org/licenses/>.
#

name: playerbasics
main: com.jeroensteenbeeke.bk.playerbasics.PlayerBasics
version: 1.0-SNAPSHOT

commands:
  help:
    description: Displays player help
    permission: playerbasics.help
    usage: /help <page|command>
  list:
    description: List all online players
    permission: playerbasics.list
    usage: /list
  rules:
    description: Lists the rules of this server
    permission: playerbasics.rules
    usage: /rules
  killme:
    description: Kills yourself
    permission: playerbasics.killme
    usage: /killme    
permissions:
    playerbasics.*:
        description: Gives access to all playerbasics commands
        default: true
        children:
            playerbasics.help: true
            playerbasics.list: true
            playerbasics.motd: true
            playerbasics.rules: true
            playerbasics.killme: true       
    playerbasics.help:
        description: Allows players to view the help
        default: true
    playerbasics.list:
        description: Allows players to view a list of members
        default: true
    playerbasics.motd:
        description: Allows players to view the MOTD 
        default: true
    playerbasics.rules:
        description: Allows players to view the rules
        default: true
    playerbasics.killme:
        description: Allows players to kill themselves
        default: true        