#
# This file is part of Jaybukkit.
#
# Jaybukkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Jaybukkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Jaybukkit.  If not, see <http://www.gnu.org/licenses/>.
#

name: colornames
main: com.jeroensteenbeeke.bk.colornames.ColorNames
version: 1.0-SNAPSHOT

permissions:
    colornames.black:
        description: Black chat text
        default: false
    colornames.dark_blue:
        description: Dark blue chat text
        default: false
    colornames.dark_green:
        description: Dark green chat text
        default: false
    colornames.dark_aqua:
        description: Dark aqua chat text
        default: false
    colornames.dark_red:
        description: Dark red chat text
        default: false
    colornames.dark_purple:
        description: Dark purple chat text
        default: false
    colornames.gold:
        description: Gold chat text
        default: false
    colornames.gray:
        description: Gray chat text
        default: false
    colornames.dark_gray:
        description: Dark gray chat text
        default: false
    colornames.blue:
        description: Blue chat text
        default: false
    colornames.green:
        description: Black chat text
        default: false
    colornames.aqua:
        description: Aqua chat text
        default: false
    colornames.red:
        description: Red chat text
        default: false
    colornames.light_purple:
        description: Light purple chat text
        default: false
    colornames.yellow:
        description: Yellow chat text
        default: false
    colornames.white:
        description: White chat text
        default: false